:url = http://localhost:3000
:email = "email": "example@localhost.com"
:password = "password": "hunter3"

:token := restclient-auth-token

# vital check
GET :url

# Bad register attempt
POST :url/register
Content-Type: application/json

# Successful register attempt
POST :url/register
Content-Type: application/json

{
    :email,
    :password
}

# Bad login attemp
POST :url/login
Content-Type: application/json

# Successful register attempt
POST :url/login
Content-Type: application/json

{
    :email,
    :password
}


# Get all reminderes
GET :url/api/reminders
authorization: :token

# Add reminder
POST :url/api/reminders
authorization: :token
Content-Type: application/json

{
	"message": "Write example oauth application"
}
